import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useAccount } from "wagmi";
import {
  Chain,
  Network,
  useMeNfTsQuery,
  SortDirection,
  TokenSortKey,
} from "../src/generated/graphql";
import { NFTPreview } from "@zoralabs/nft-components";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data: accountData } = useAccount();
  const { data } = useMeNfTsQuery({
    variables: {
      where: {
        ownerAddresses: accountData?.address ? [accountData?.address] : [],
      },
      pagination: {
        limit: 40,
      },
      networks: [{ chain: Chain.Mainnet, network: Network.Ethereum }],
      sort: {
        sortDirection: SortDirection.Asc,
        sortKey: TokenSortKey.Transferred,
      },
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App with ZDK Zora Dev Kit GraphQL API</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{" "}
          <a href="">Zora GraphQL API</a> +{" "}
          <a href="">Apollo Hooks with Codegen</a> +{" "}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://rainbowkit.com" className={styles.card}>
            <h2>RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a href="https://wagmi.sh" className={styles.card}>
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            href="https://github.com/rainbow-me/rainbowkit-examples"
            className={styles.card}
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <div className={styles.grid}>
        {data?.tokens.nodes.map(({ token }) => (
          <div key={token.tokenId}>
            <NFTPreview contract={token.collectionAddress} id={token.tokenId} />
          </div>
        ))}
      </div>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
