import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import error from "next/error";
import Head from "next/head";
import {
  useCollectionInfoQuery,
  CollectionSortKey,
  SortDirection,
  Chain,
  Network,
} from "../src/generated/graphql";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data, loading, error } = useCollectionInfoQuery({
    variables: {
      networks: [{ chain: Chain.Mainnet, network: Network.Ethereum }],
      pagination: {
        limit: 10,
      },
      sort: {
        sortKey: CollectionSortKey.Created,
        sortDirection: SortDirection.Desc,
      },
      where: {
        collectionAddresses: ["0xc729Ce9bF1030fbb639849a96fA8BBD013680B64"],
      },
    },
  });

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App with ZDK Zora Dev Kit GraphQL API</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{" "}
          <a href="">ZDK</a> + <a href="https://nextjs.org">Next.js!</a>
          {JSON.stringify(data, null, 2)}
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://rainbowkit.com" className={styles.card}>
            <h2>RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a href="https://wagmi.sh" className={styles.card}>
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            href="https://github.com/rainbow-me/rainbowkit-examples"
            className={styles.card}
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
